### ISSUE TITLE
[Feature request]: [ecl/sorting] Postal code sorting

### ISSUE THREAD

**Issue by Rene-63** [LSS-Manager/LSSM-V.4#2281] opened 2023-04-16 06:07 UTC
### Is your feature related to a problem?

When closing the team notifications, I have to select notifications from the map to handle notifications in a certain area. I choose this because a large number of team members do not have national coverage and therefore have too long driving times for those reports.

### Solution / Feature

Add the Postal code sorting option in the extended notification list

**Comment by Cr4zyc4k3** [comment] 2023-04-16 06:13
This is very tricky since post codes are varying in different countries. https://en.wikipedia.org/wiki/Postal_code?wprov=sfla1

And even if we managend to find a working algorithm: How do we sort by a zip code? Set a number (eg. 52070) and first everything with a difference by 1 (52069, 52071) and so on?

**Comment by jxn-30** [comment] 2023-04-16 06:20
> This is very tricky since post codes are varying in different countries. https://en.wikipedia.org/wiki/Postal_code?wprov=sfla1

I don't see this such a huge problem.
We already do have a method to remove the ZIP-Code / Postal-Codes of all countries supported by LSSM (adding more on request is possible of course) so the step to extracting it should not be difficult:
https://github.com/LSS-Manager/LSSM-V.4/blob/4e80adfe3f60457ce4082267e077bd5e13b2c81e/src/modules/shareAlliancePost/assets/util.ts#L17-L32

> And even if we managend to find a working algorithm: How do we sort by a zip code? Set a number (eg. 52070) and first everything with a difference by 1 (52069, 52071) and so on?

How about simple and stupid sorting by alphabetic order? That should still produce a result that groups by similarity of ZIP-Codes which is the most advantage this sorting could give.
At least if there isn't a country that uses ZIP-Codes that represent any sorting (north→south, east→west, distance to capital, ...) any sorting will not bring more advantage then grouping :wink:

**Comment by Rene-63** [comment] 2023-04-16 12:15
Indeed, a simple numerical sort by zip code is enough. Then it is just jumping in the list to the desired postcode area. 
Postal code classified according to distance to the capital can be a problem. That country should change that :-)
I've looked at a number of countries on https://worldpostalcode.com/ and really only come across region/locally grouped postcodes

**Comment by jxn-30** [comment] 2023-06-26 15:17
@Rene-63 that feature is live on `beta` now.
Please test whether it works well, especially regarding the performance. I tested it with a list of ~ 600 missions, and it went pretty well, but more testing is probably better :)

Also there may be some issues with ZIP-Codes / Postcodes in the UK as the game does not always resolve the full and correct Postcode, thus LSSM doesn't parse the full Postcode. This is about to be changed in the game, once they updated their map/routing data in the background, which will hopefully be within the next 500 years :)

**Comment by bagman002** [comment] 2023-06-26 22:43
Hi Team. I am not sure if this update caused the issue or not but I am running the beta version. And this morning now the no value items are showing ahead of the max value items when sorting by credits

![image](https://github.com/LSS-Manager/LSSM-V.4/assets/66065321/7aeabcf2-496e-4f34-a250-b1d6d3bc69e6)

Whereas on the stable version the sorting is fine. I do however like the change to the layout of the beta release with the Accending and decending in line with the filter making the drop down box smaller

**Comment by jxn-30** [comment] 2023-06-26 22:59
This indeed seems to be a regression introduced with the update. Thanks for reporting!
We will have a look at this as soon as possible and will inform you here when there are updates about this. 😊

**Comment by Rene-63** [comment] 2023-06-27 07:16
@jxn-30 I ran the sorting by zip code with a list of 2,200 missions. For now, the speed is as usual.

**Comment by jxn-30** [comment] 2023-06-27 09:29
@bagman002 should be fixed on beta now

**Comment by bagman002** [comment] 2023-06-27 10:24
> @bagman002 should be fixed on beta now

Thanks this is fixed now

**Closed** 2023-07-05 07:38 UTC
Labels: enhancement
